enum ActionType {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REFRESH = "REFRESH",
  INCREASE_ARTICLE_CART = "INCREASE_ARTICLE_CART",
  REMOVE_ARTICLE_CART = "REMOVE_ARTICLE_CART",
  UPDATE_ARTICLE_CART = "UPDATE_ARTICLE_CART",
  ADD_ARTICLE_CART = "ADD_ARTICLE_CART",
  CLEAR_CART = "CLEAR_CART",
  GET_ALL_ARTICLES = "GET_ALL_ARTICLES",
  GET_ALL_ORDERS = "GET_ALL_ORDERS",
}

export default ActionType;
